name: publish-library

on:
  workflow_call:
    inputs:
      registryRepositoryName: 
        type: string  
        default: "core-oci-local"
      registryHost:
        type: string
        default: "farmer.jfrog.io"
      chartDirectory:
        type: string
        default: "./chart"  

    secrets:
      username: 
        required: true
      password:
        required: true        

jobs:

  get-chart-version:
    runs-on: ubuntu-latest
    outputs: 
      chartVersion: ${{ steps.get-semantic-version.outputs.group1 }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@releases/v2
        
    - name: SEMVER - Load
      id: read-properties
      uses: juliangruber/read-file-action@v1
      with:
        path: ${{ inputs.chartDirectory }}/Chart.yaml 
        
    - name: SEMVER - Determine.
      id: get-semantic-version
      uses: actions-ecosystem/action-regex-match@v2
      with:
        text: ${{ steps.read-properties.outputs.content }}
        regex: 'version: (.*)'    

  get-chart-name:
    runs-on: ubuntu-latest
    outputs: 
      chartName: ${{ steps.get-chart-name.outputs.group1 }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@releases/v2
        
    - name: SEMVER - Load
      id: read-properties
      uses: juliangruber/read-file-action@v1
      with:
        path: ${{ inputs.chartDirectory }}/Chart.yaml 
        
    - name: SEMVER - Determine.
      id: get-chart-name
      uses: actions-ecosystem/action-regex-match@v2
      with:
        text: ${{ steps.read-properties.outputs.content }}
        regex: 'name: (.*)'    
  
  publish:
    runs-on: ubuntu-latest
    needs:
    - get-chart-version
    - get-chart-name
    container:
      image: alpine/helm:3.10.2
    steps:
    - name: Check out the repo
      uses: actions/checkout@releases/v2

    - name: HELM - Package
      run: helm package ${{ inputs.chartDirectory }}

    - name: HELM - Login
      run: helm registry login -u ${{ secrets.username }} -p ${{ secrets.password }} ${{ inputs.registryHost }}

    - name: HELM - Push
      run: helm push ${{ needs.get-chart-name.outputs.chartName }}.${{ needs.get-chart-version.outputs.chartVersion }}.tgz oci://${{ inputs.registryHost }}/${{ inputs.registryRepositoryName }}